# validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

# partial line support
parsers:
  javascript:
    enable_partials: yes

# docs:
#   https://docs.codecov.io/docs/commit-status
#   https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a
coverage:
  status:
    project:
      default:
        threshold: 1%
        if_not_found: success  # no commit found? still set a success
    patch:
      default:
        if_not_found: success
